// Template definitions for store types
export interface CanvasElement {
  id: string;
  type: 'text' | 'image' | 'button' | 'container';
  content?: string;
  x: number;
  y: number;
  width: number;
  height: number;
  color?: string;
  backgroundColor?: string;
  fontSize?: number;
}

export const TEMPLATE_ELEMENTS: Record<string, CanvasElement[]> = {
  minimal: [
    {
      id: 'header',
      type: 'container',
      content: '',
      x: 0,
      y: 0,
      width: 1000,
      height: 72,
      backgroundColor: '#ffffff',
    },
    {
      id: 'logo',
      type: 'text',
      content: 'COMMERCE',
      x: 40,
      y: 16,
      width: 200,
      height: 40,
      fontSize: 26,
      color: '#1a1a1a',
    },
    {
      id: 'nav-home',
      type: 'button',
      content: 'HOME',
      x: 360,
      y: 21,
      width: 55,
      height: 28,
      color: '#4a4a4a',
      backgroundColor: 'transparent',
      fontSize: 13,
    },
    {
      id: 'nav-shop',
      type: 'button',
      content: 'SHOP',
      x: 435,
      y: 21,
      width: 55,
      height: 28,
      color: '#4a4a4a',
      backgroundColor: 'transparent',
      fontSize: 13,
    },
    {
      id: 'nav-about',
      type: 'button',
      content: 'ABOUT',
      x: 510,
      y: 21,
      width: 55,
      height: 28,
      color: '#4a4a4a',
      backgroundColor: 'transparent',
      fontSize: 13,
    },
    {
      id: 'nav-cart',
      type: 'button',
      content: 'CART',
      x: 585,
      y: 21,
      width: 55,
      height: 28,
      color: '#4a4a4a',
      backgroundColor: 'transparent',
      fontSize: 13,
    },
    {
      id: 'hero-image',
      type: 'container',
      content: '▱ ▱ ▱ ▱ ▱\n▱ New Arrivals ▱\n▱ ▱ ▱ ▱ ▱',
      x: 280,
      y: 100,
      width: 440,
      height: 160,
      backgroundColor: '#e8e8e8',
      color: '#999999',
      fontSize: 14,
    },
    {
      id: 'hero-cta',
      type: 'button',
      content: 'NEW ARRIVALS - DISCOVER MORE →',
      x: 280,
      y: 275,
      width: 440,
      height: 42,
      color: '#1a1a1a',
      backgroundColor: '#ffffff',
      fontSize: 11,
    },
    {
      id: 'divider-1',
      type: 'container',
      content: '',
      x: 0,
      y: 345,
      width: 1000,
      height: 1,
      backgroundColor: '#e8e8e8',
    },
    {
      id: 'products-title',
      type: 'text',
      content: 'Featured Products',
      x: 40,
      y: 365,
      width: 400,
      height: 32,
      fontSize: 22,
      color: '#1a1a1a',
    },
    {
      id: 'product-1-img',
      type: 'container',
      content: '👕',
      x: 40,
      y: 420,
      width: 200,
      height: 140,
      backgroundColor: '#f5f5f5',
      fontSize: 60,
    },
    {
      id: 'product-1-name',
      type: 'text',
      content: 'Product Name',
      x: 40,
      y: 570,
      width: 200,
      height: 24,
      fontSize: 14,
      color: '#1a1a1a',
    },
    {
      id: 'product-1-price',
      type: 'text',
      content: '$XX.XX',
      x: 40,
      y: 600,
      width: 200,
      height: 22,
      fontSize: 16,
      color: '#1a1a1a',
    },
    {
      id: 'product-1-btn',
      type: 'button',
      content: 'ADD TO CART',
      x: 40,
      y: 635,
      width: 200,
      height: 40,
      backgroundColor: '#ffffff',
      color: '#1a1a1a',
      fontSize: 11,
    },
    {
      id: 'product-2-img',
      type: 'container',
      content: '👔',
      x: 260,
      y: 420,
      width: 200,
      height: 140,
      backgroundColor: '#f5f5f5',
      fontSize: 60,
    },
    {
      id: 'product-2-name',
      type: 'text',
      content: 'Product Name',
      x: 260,
      y: 570,
      width: 200,
      height: 24,
      fontSize: 14,
      color: '#1a1a1a',
    },
    {
      id: 'product-2-price',
      type: 'text',
      content: '$XX.XX',
      x: 260,
      y: 600,
      width: 200,
      height: 22,
      fontSize: 16,
      color: '#1a1a1a',
    },
    {
      id: 'product-2-btn',
      type: 'button',
      content: 'ADD TO CART',
      x: 260,
      y: 635,
      width: 200,
      height: 40,
      backgroundColor: '#ffffff',
      color: '#1a1a1a',
      fontSize: 11,
    },
    {
      id: 'product-3-img',
      type: 'container',
      content: '👟',
      x: 480,
      y: 420,
      width: 200,
      height: 140,
      backgroundColor: '#f5f5f5',
      fontSize: 60,
    },
    {
      id: 'product-3-name',
      type: 'text',
      content: 'Product Name',
      x: 480,
      y: 570,
      width: 200,
      height: 24,
      fontSize: 14,
      color: '#1a1a1a',
    },
    {
      id: 'product-3-price',
      type: 'text',
      content: '$XX.XX',
      x: 480,
      y: 600,
      width: 200,
      height: 22,
      fontSize: 16,
      color: '#1a1a1a',
    },
    {
      id: 'product-3-btn',
      type: 'button',
      content: 'ADD TO CART',
      x: 480,
      y: 635,
      width: 200,
      height: 40,
      backgroundColor: '#ffffff',
      color: '#1a1a1a',
      fontSize: 11,
    },
    {
      id: 'product-4-img',
      type: 'container',
      content: '🎒',
      x: 700,
      y: 420,
      width: 200,
      height: 140,
      backgroundColor: '#f5f5f5',
      fontSize: 60,
    },
    {
      id: 'product-4-name',
      type: 'text',
      content: 'Product Name',
      x: 700,
      y: 570,
      width: 200,
      height: 24,
      fontSize: 14,
      color: '#1a1a1a',
    },
    {
      id: 'product-4-price',
      type: 'text',
      content: '$XX.XX',
      x: 700,
      y: 600,
      width: 200,
      height: 22,
      fontSize: 16,
      color: '#1a1a1a',
    },
    {
      id: 'product-4-btn',
      type: 'button',
      content: 'ADD TO CART',
      x: 700,
      y: 635,
      width: 200,
      height: 40,
      backgroundColor: '#ffffff',
      color: '#1a1a1a',
      fontSize: 11,
    },
    {
      id: 'promo',
      type: 'container',
      content: 'FREE SHIPPING ON ALL ORDERS OVER $50',
      x: 40,
      y: 715,
      width: 920,
      height: 45,
      backgroundColor: '#f5f5f5',
      color: '#1a1a1a',
      fontSize: 12,
    },
    {
      id: 'footer',
      type: 'container',
      content: '',
      x: 0,
      y: 800,
      width: 1000,
      height: 100,
      backgroundColor: '#f0f0f0',
    },
    {
      id: 'footer-quick',
      type: 'text',
      content: 'QUICK LINKS\n• FAQ\n• TRACK ORDER',
      x: 40,
      y: 820,
      width: 280,
      height: 60,
      fontSize: 11,
      color: '#1a1a1a',
    },
    {
      id: 'footer-company',
      type: 'text',
      content: 'COMPANY\n• CAREERS\n• PRESS',
      x: 360,
      y: 820,
      width: 280,
      height: 60,
      fontSize: 11,
      color: '#1a1a1a',
    },
    {
      id: 'footer-social',
      type: 'text',
      content: 'SOCIAL\n f  𝕏',
      x: 680,
      y: 820,
      width: 280,
      height: 60,
      fontSize: 11,
      color: '#1a1a1a',
    },
  ],
  marketplace: [
    {
      id: 'header',
      type: 'container',
      content: '',
      x: 0,
      y: 0,
      width: 1000,
      height: 70,
      backgroundColor: '#ffffff',
    },
    {
      id: 'logo',
      type: 'text',
      content: 'MarketHub',
      x: 40,
      y: 15,
      width: 300,
      height: 40,
      fontSize: 28,
      color: '#0066cc',
    },
    {
      id: 'search',
      type: 'container',
      content: '🔍 Search products, vendors...',
      x: 400,
      y: 15,
      width: 450,
      height: 40,
      backgroundColor: '#f5f5f5',
      color: '#999999',
      fontSize: 12,
    },
    {
      id: 'hero',
      type: 'container',
      content: '',
      x: 0,
      y: 80,
      width: 1000,
      height: 160,
      backgroundColor: '#0066cc',
    },
    {
      id: 'hero-text',
      type: 'text',
      content: 'Discover Thousands of Sellers\nShop from Trusted Vendors',
      x: 40,
      y: 100,
      width: 920,
      height: 120,
      fontSize: 32,
      color: '#ffffff',
    },
    {
      id: 'cat-title',
      type: 'text',
      content: 'Shop by Category',
      x: 40,
      y: 270,
      width: 400,
      height: 30,
      fontSize: 24,
      color: '#1a1a1a',
    },
    {
      id: 'cat1',
      type: 'button',
      content: 'Electronics',
      x: 40,
      y: 320,
      width: 170,
      height: 50,
      backgroundColor: '#e8e8e8',
      color: '#1a1a1a',
      fontSize: 14,
    },
    {
      id: 'cat2',
      type: 'button',
      content: 'Fashion',
      x: 230,
      y: 320,
      width: 170,
      height: 50,
      backgroundColor: '#e8e8e8',
      color: '#1a1a1a',
      fontSize: 14,
    },
    {
      id: 'cat3',
      type: 'button',
      content: 'Home & Garden',
      x: 420,
      y: 320,
      width: 170,
      height: 50,
      backgroundColor: '#e8e8e8',
      color: '#1a1a1a',
      fontSize: 14,
    },
    {
      id: 'cat4',
      type: 'button',
      content: 'Sports',
      x: 610,
      y: 320,
      width: 170,
      height: 50,
      backgroundColor: '#e8e8e8',
      color: '#1a1a1a',
      fontSize: 14,
    },
    {
      id: 'cat5',
      type: 'button',
      content: 'Beauty',
      x: 800,
      y: 320,
      width: 160,
      height: 50,
      backgroundColor: '#e8e8e8',
      color: '#1a1a1a',
      fontSize: 14,
    },
    {
      id: 'vendor-title',
      type: 'text',
      content: 'Featured Vendors',
      x: 40,
      y: 400,
      width: 400,
      height: 30,
      fontSize: 24,
      color: '#1a1a1a',
    },
    {
      id: 'vendor1',
      type: 'container',
      content: '⚡\nPremium Electronics\n★★★★★ (1,234)\n500+ Products',
      x: 40,
      y: 450,
      width: 220,
      height: 180,
      backgroundColor: '#f9f9f9',
      fontSize: 40,
      color: '#1a1a1a',
    },
    {
      id: 'vendor2',
      type: 'container',
      content: '👗\nFashion Forward\n★★★★★ (2,156)\n300+ Products',
      x: 280,
      y: 450,
      width: 220,
      height: 180,
      backgroundColor: '#f9f9f9',
      fontSize: 40,
      color: '#1a1a1a',
    },
    {
      id: 'vendor3',
      type: 'container',
      content: '🏠\nHome Essentials\n★★★★☆ (892)\n450+ Products',
      x: 520,
      y: 450,
      width: 220,
      height: 180,
      backgroundColor: '#f9f9f9',
      fontSize: 40,
      color: '#1a1a1a',
    },
    {
      id: 'vendor4',
      type: 'container',
      content: '⚽\nSports Hub\n★★★★★ (1,567)\n320+ Products',
      x: 760,
      y: 450,
      width: 200,
      height: 180,
      backgroundColor: '#f9f9f9',
      fontSize: 40,
      color: '#1a1a1a',
    },
    {
      id: 'deals-title',
      type: 'text',
      content: 'Best Deals Today',
      x: 40,
      y: 670,
      width: 920,
      height: 30,
      fontSize: 24,
      color: '#1a1a1a',
    },
    {
      id: 'deal1',
      type: 'container',
      content: '📱\n50% OFF\n\nSmartphone\n$29.99',
      x: 40,
      y: 720,
      width: 210,
      height: 260,
      backgroundColor: '#ffffff',
      fontSize: 30,
      color: '#ff4444',
    },
    {
      id: 'deal2',
      type: 'container',
      content: '👕\n30% OFF\n\nClothing\n$34.99',
      x: 270,
      y: 720,
      width: 210,
      height: 260,
      backgroundColor: '#ffffff',
      fontSize: 30,
      color: '#ff4444',
    },
    {
      id: 'deal3',
      type: 'container',
      content: '👟\n25% OFF\n\nShoes\n$74.99',
      x: 500,
      y: 720,
      width: 210,
      height: 260,
      backgroundColor: '#ffffff',
      fontSize: 30,
      color: '#ff4444',
    },
    {
      id: 'deal4',
      type: 'container',
      content: '🎮\n45% OFF\n\nGaming Gear\n$54.99',
      x: 730,
      y: 720,
      width: 210,
      height: 260,
      backgroundColor: '#ffffff',
      fontSize: 30,
      color: '#ff4444',
    },
    {
      id: 'footer',
      type: 'container',
      content: '',
      x: 0,
      y: 1020,
      width: 1000,
      height: 80,
      backgroundColor: '#1a1a1a',
    },
    {
      id: 'footer-text',
      type: 'text',
      content: 'Become a Seller | Terms & Conditions | Privacy Policy | Contact Us\n© 2024 MarketHub. All Rights Reserved.',
      x: 40,
      y: 1035,
      width: 920,
      height: 50,
      fontSize: 11,
      color: '#ffffff',
    },
  ],
  tech: [
    {
      id: 'header',
      type: 'container',
      content: '',
      x: 0,
      y: 0,
      width: 1000,
      height: 70,
      backgroundColor: '#1a1a1a',
    },
    {
      id: 'logo',
      type: 'text',
      content: 'TechGear',
      x: 40,
      y: 15,
      width: 300,
      height: 40,
      fontSize: 26,
      color: '#00d4ff',
    },
    {
      id: 'nav1',
      type: 'button',
      content: 'SHOP',
      x: 650,
      y: 20,
      width: 70,
      height: 30,
      backgroundColor: 'transparent',
      color: '#ffffff',
      fontSize: 12,
    },
    {
      id: 'nav2',
      type: 'button',
      content: 'SPECS',
      x: 730,
      y: 20,
      width: 70,
      height: 30,
      backgroundColor: 'transparent',
      color: '#ffffff',
      fontSize: 12,
    },
    {
      id: 'nav3',
      type: 'button',
      content: 'DEALS',
      x: 810,
      y: 20,
      width: 70,
      height: 30,
      backgroundColor: 'transparent',
      color: '#ffffff',
      fontSize: 12,
    },
    {
      id: 'nav4',
      type: 'button',
      content: 'SUPPORT',
      x: 890,
      y: 20,
      width: 70,
      height: 30,
      backgroundColor: 'transparent',
      color: '#ffffff',
      fontSize: 12,
    },
    {
      id: 'hero',
      type: 'container',
      content: '',
      x: 0,
      y: 80,
      width: 1000,
      height: 200,
      backgroundColor: '#00d4ff',
    },
    {
      id: 'hero-text',
      type: 'text',
      content: 'Latest Tech Gadgets\nPerformance Meets Innovation',
      x: 60,
      y: 110,
      width: 880,
      height: 100,
      fontSize: 40,
      color: '#000000',
    },
    {
      id: 'search',
      type: 'container',
      content: '🔍 Search products by brand...',
      x: 80,
      y: 300,
      width: 840,
      height: 45,
      backgroundColor: '#f0f0f0',
      color: '#999999',
      fontSize: 12,
    },
    {
      id: 'filter-title',
      type: 'text',
      content: 'Filter by Category',
      x: 40,
      y: 370,
      width: 300,
      height: 30,
      fontSize: 18,
      color: '#1a1a1a',
    },
    {
      id: 'filter1',
      type: 'button',
      content: '💻 Laptops',
      x: 40,
      y: 420,
      width: 210,
      height: 45,
      backgroundColor: '#e8e8e8',
      color: '#1a1a1a',
      fontSize: 13,
    },
    {
      id: 'filter2',
      type: 'button',
      content: '📱 Smartphones',
      x: 270,
      y: 420,
      width: 210,
      height: 45,
      backgroundColor: '#e8e8e8',
      color: '#1a1a1a',
      fontSize: 13,
    },
    {
      id: 'filter3',
      type: 'button',
      content: '�� Audio',
      x: 500,
      y: 420,
      width: 210,
      height: 45,
      backgroundColor: '#e8e8e8',
      color: '#1a1a1a',
      fontSize: 13,
    },
    {
      id: 'filter4',
      type: 'button',
      content: '⌚ Wearables',
      x: 730,
      y: 420,
      width: 210,
      height: 45,
      backgroundColor: '#e8e8e8',
      color: '#1a1a1a',
      fontSize: 13,
    },
    {
      id: 'featured-title',
      type: 'text',
      content: 'Featured Products',
      x: 40,
      y: 490,
      width: 400,
      height: 30,
      fontSize: 24,
      color: '#1a1a1a',
    },
    {
      id: 'product1',
      type: 'container',
      content: '💻\nPremium Laptop\n16GB | 512GB\n$1,299.99\n⭐⭐⭐⭐⭐',
      x: 40,
      y: 540,
      width: 220,
      height: 280,
      backgroundColor: '#ffffff',
      fontSize: 30,
      color: '#1a1a1a',
    },
    {
      id: 'product2',
      type: 'container',
      content: '📱\nFlagship Phone\n8GB | 128GB\n$899.99\n⭐⭐⭐⭐⭐',
      x: 280,
      y: 540,
      width: 220,
      height: 280,
      backgroundColor: '#ffffff',
      fontSize: 30,
      color: '#1a1a1a',
    },
    {
      id: 'product3',
      type: 'container',
      content: '🎧\nWireless Buds\nPremium Audio\n$349.99\n⭐⭐⭐⭐☆',
      x: 520,
      y: 540,
      width: 220,
      height: 280,
      backgroundColor: '#ffffff',
      fontSize: 30,
      color: '#1a1a1a',
    },
    {
      id: 'product4',
      type: 'container',
      content: '⌚\nSmartwatch\n5G Ready\n$799.99\n⭐⭐⭐⭐⭐',
      x: 760,
      y: 540,
      width: 200,
      height: 280,
      backgroundColor: '#ffffff',
      fontSize: 30,
      color: '#1a1a1a',
    },
    {
      id: 'compare',
      type: 'container',
      content: '⚔️ Compare Products Side-by-Side',
      x: 40,
      y: 860,
      width: 920,
      height: 100,
      backgroundColor: '#f0f0f0',
      color: '#1a1a1a',
      fontSize: 16,
    },
    {
      id: 'footer',
      type: 'container',
      content: '',
      x: 0,
      y: 1000,
      width: 1000,
      height: 80,
      backgroundColor: '#1a1a1a',
    },
    {
      id: 'footer-text',
      type: 'text',
      content: '© 2024 TechGear. Premium Tech | Free Shipping | 2-Year Warranty\nSupport: support@techgear.com | 1-800-TECH-123',
      x: 40,
      y: 1015,
      width: 920,
      height: 50,
      fontSize: 11,
      color: '#00d4ff',
    },
  ],
};
