// Template definitions for store types
export interface CanvasElement {
  id: string;
  type: 'text' | 'image' | 'button' | 'container';
  content?: string;
  x: number;
  y: number;
  width: number;
  height: number;
  color?: string;
  backgroundColor?: string;
  fontSize?: number;
}

export const TEMPLATE_ELEMENTS: Record<string, CanvasElement[]> = {
  minimal: [
    {
      id: 'header',
      type: 'container',
      content: '',
      x: 0,
      y: 0,
      width: 1000,
      height: 72,
      backgroundColor: '#ffffff',
    },
    {
      id: 'logo',
      type: 'text',
      content: 'COMMERCE',
      x: 40,
      y: 16,
      width: 200,
      height: 40,
      fontSize: 26,
      color: '#1a1a1a',
    },
    {
      id: 'nav-home',
      type: 'button',
      content: 'HOME',
      x: 360,
      y: 21,
      width: 55,
      height: 28,
      color: '#4a4a4a',
      backgroundColor: 'transparent',
      fontSize: 13,
    },
    {
      id: 'nav-shop',
      type: 'button',
      content: 'SHOP',
      x: 435,
      y: 21,
      width: 55,
      height: 28,
      color: '#4a4a4a',
      backgroundColor: 'transparent',
      fontSize: 13,
    },
    {
      id: 'nav-about',
      type: 'button',
      content: 'ABOUT',
      x: 510,
      y: 21,
      width: 55,
      height: 28,
      color: '#4a4a4a',
      backgroundColor: 'transparent',
      fontSize: 13,
    },
    {
      id: 'nav-cart',
      type: 'button',
      content: 'CART',
      x: 585,
      y: 21,
      width: 55,
      height: 28,
      color: '#4a4a4a',
      backgroundColor: 'transparent',
      fontSize: 13,
    },
    {
      id: 'hero-image',
      type: 'container',
      content: '▱ ▱ ▱ ▱ ▱\n▱ New Arrivals ▱\n▱ ▱ ▱ ▱ ▱',
      x: 280,
      y: 100,
      width: 440,
      height: 160,
      backgroundColor: '#e8e8e8',
      color: '#999999',
      fontSize: 14,
    },
    {
      id: 'hero-cta',
      type: 'button',
      content: 'NEW ARRIVALS - DISCOVER MORE →',
      x: 280,
      y: 275,
      width: 440,
      height: 42,
      color: '#1a1a1a',
      backgroundColor: '#ffffff',
      fontSize: 11,
    },
    {
      id: 'divider-1',
      type: 'container',
      content: '',
      x: 0,
      y: 345,
      width: 1000,
      height: 1,
      backgroundColor: '#e8e8e8',
    },
    {
      id: 'products-title',
      type: 'text',
      content: 'Featured Products',
      x: 40,
      y: 365,
      width: 400,
      height: 32,
      fontSize: 22,
      color: '#1a1a1a',
    },
    {
      id: 'product-1-img',
      type: 'container',
      content: '👕',
      x: 40,
      y: 420,
      width: 200,
      height: 140,
      backgroundColor: '#f5f5f5',
      fontSize: 60,
    },
    {
      id: 'product-1-name',
      type: 'text',
      content: 'Product Name',
      x: 40,
      y: 570,
      width: 200,
      height: 24,
      fontSize: 14,
      color: '#1a1a1a',
    },
    {
      id: 'product-1-price',
      type: 'text',
      content: '$XX.XX',
      x: 40,
      y: 600,
      width: 200,
      height: 22,
      fontSize: 16,
      color: '#1a1a1a',
    },
    {
      id: 'product-1-btn',
      type: 'button',
      content: 'ADD TO CART',
      x: 40,
      y: 635,
      width: 200,
      height: 40,
      backgroundColor: '#ffffff',
      color: '#1a1a1a',
      fontSize: 11,
    },
    {
      id: 'product-2-img',
      type: 'container',
      content: '👔',
      x: 260,
      y: 420,
      width: 200,
      height: 140,
      backgroundColor: '#f5f5f5',
      fontSize: 60,
    },
    {
      id: 'product-2-name',
      type: 'text',
      content: 'Product Name',
      x: 260,
      y: 570,
      width: 200,
      height: 24,
      fontSize: 14,
      color: '#1a1a1a',
    },
    {
      id: 'product-2-price',
      type: 'text',
      content: '$XX.XX',
      x: 260,
      y: 600,
      width: 200,
      height: 22,
      fontSize: 16,
      color: '#1a1a1a',
    },
    {
      id: 'product-2-btn',
      type: 'button',
      content: 'ADD TO CART',
      x: 260,
      y: 635,
      width: 200,
      height: 40,
      backgroundColor: '#ffffff',
      color: '#1a1a1a',
      fontSize: 11,
    },
    {
      id: 'product-3-img',
      type: 'container',
      content: '👟',
      x: 480,
      y: 420,
      width: 200,
      height: 140,
      backgroundColor: '#f5f5f5',
      fontSize: 60,
    },
    {
      id: 'product-3-name',
      type: 'text',
      content: 'Product Name',
      x: 480,
      y: 570,
      width: 200,
      height: 24,
      fontSize: 14,
      color: '#1a1a1a',
    },
    {
      id: 'product-3-price',
      type: 'text',
      content: '$XX.XX',
      x: 480,
      y: 600,
      width: 200,
      height: 22,
      fontSize: 16,
      color: '#1a1a1a',
    },
    {
      id: 'product-3-btn',
      type: 'button',
      content: 'ADD TO CART',
      x: 480,
      y: 635,
      width: 200,
      height: 40,
      backgroundColor: '#ffffff',
      color: '#1a1a1a',
      fontSize: 11,
    },
    {
      id: 'product-4-img',
      type: 'container',
      content: '🎒',
      x: 700,
      y: 420,
      width: 200,
      height: 140,
      backgroundColor: '#f5f5f5',
      fontSize: 60,
    },
    {
      id: 'product-4-name',
      type: 'text',
      content: 'Product Name',
      x: 700,
      y: 570,
      width: 200,
      height: 24,
      fontSize: 14,
      color: '#1a1a1a',
    },
    {
      id: 'product-4-price',
      type: 'text',
      content: '$XX.XX',
      x: 700,
      y: 600,
      width: 200,
      height: 22,
      fontSize: 16,
      color: '#1a1a1a',
    },
    {
      id: 'product-4-btn',
      type: 'button',
      content: 'ADD TO CART',
      x: 700,
      y: 635,
      width: 200,
      height: 40,
      backgroundColor: '#ffffff',
      color: '#1a1a1a',
      fontSize: 11,
    },
    {
      id: 'promo',
      type: 'container',
      content: 'FREE SHIPPING ON ALL ORDERS OVER $50',
      x: 40,
      y: 715,
      width: 920,
      height: 45,
      backgroundColor: '#f5f5f5',
      color: '#1a1a1a',
      fontSize: 12,
    },
    {
      id: 'footer',
      type: 'container',
      content: '',
      x: 0,
      y: 800,
      width: 1000,
      height: 100,
      backgroundColor: '#f0f0f0',
    },
    {
      id: 'footer-quick',
      type: 'text',
      content: 'QUICK LINKS\n• FAQ\n• TRACK ORDER',
      x: 40,
      y: 820,
      width: 280,
      height: 60,
      fontSize: 11,
      color: '#1a1a1a',
    },
    {
      id: 'footer-company',
      type: 'text',
      content: 'COMPANY\n• CAREERS\n• PRESS',
      x: 360,
      y: 820,
      width: 280,
      height: 60,
      fontSize: 11,
      color: '#1a1a1a',
    },
    {
      id: 'footer-social',
      type: 'text',
      content: 'SOCIAL\n f  𝕏',
      x: 680,
      y: 820,
      width: 280,
      height: 60,
      fontSize: 11,
      color: '#1a1a1a',
    },
  ],
  marketplace: [
    {
      id: 'header',
      type: 'container',
      content: '',
      x: 0,
      y: 0,
      width: 1000,
      height: 70,
      backgroundColor: '#ffffff',
    },
    {
      id: 'logo',
      type: 'text',
      content: 'MarketHub',
      x: 40,
      y: 15,
      width: 300,
      height: 40,
      fontSize: 28,
      color: '#0066cc',
    },
    {
      id: 'search',
      type: 'container',
      content: '🔍 Search products, vendors...',
      x: 400,
      y: 15,
      width: 450,
      height: 40,
      backgroundColor: '#f5f5f5',
      color: '#999999',
      fontSize: 12,
    },
    {
      id: 'hero',
      type: 'container',
      content: '',
      x: 0,
      y: 80,
      width: 1000,
      height: 160,
      backgroundColor: '#0066cc',
    },
    {
      id: 'hero-text',
      type: 'text',
      content: 'Discover Thousands of Sellers\nShop from Trusted Vendors',
      x: 40,
      y: 100,
      width: 920,
      height: 120,
      fontSize: 32,
      color: '#ffffff',
    },
    {
      id: 'cat-title',
      type: 'text',
      content: 'Shop by Category',
      x: 40,
      y: 270,
      width: 400,
      height: 30,
      fontSize: 24,
      color: '#1a1a1a',
    },
    {
      id: 'cat1',
      type: 'button',
      content: 'Electronics',
      x: 40,
      y: 320,
      width: 170,
      height: 50,
      backgroundColor: '#e8e8e8',
      color: '#1a1a1a',
      fontSize: 14,
    },
    {
      id: 'cat2',
      type: 'button',
      content: 'Fashion',
      x: 230,
      y: 320,
      width: 170,
      height: 50,
      backgroundColor: '#e8e8e8',
      color: '#1a1a1a',
      fontSize: 14,
    },
    {
      id: 'cat3',
      type: 'button',
      content: 'Home & Garden',
      x: 420,
      y: 320,
      width: 170,
      height: 50,
      backgroundColor: '#e8e8e8',
      color: '#1a1a1a',
      fontSize: 14,
    },
    {
      id: 'cat4',
      type: 'button',
      content: 'Sports',
      x: 610,
      y: 320,
      width: 170,
      height: 50,
      backgroundColor: '#e8e8e8',
      color: '#1a1a1a',
      fontSize: 14,
    },
    {
      id: 'cat5',
      type: 'button',
      content: 'Beauty',
      x: 800,
      y: 320,
      width: 160,
      height: 50,
      backgroundColor: '#e8e8e8',
      color: '#1a1a1a',
      fontSize: 14,
    },
    {
      id: 'vendor-title',
      type: 'text',
      content: 'Featured Vendors',
      x: 40,
      y: 400,
      width: 400,
      height: 30,
      fontSize: 24,
      color: '#1a1a1a',
    },
    {
      id: 'vendor1',
      type: 'container',
      content: '⚡\nPremium Electronics\n★★★★★ (1,234)\n500+ Products',
      x: 40,
      y: 450,
      width: 220,
      height: 180,
      backgroundColor: '#f9f9f9',
      fontSize: 40,
      color: '#1a1a1a',
    },
    {
      id: 'vendor2',
      type: 'container',
      content: '👗\nFashion Forward\n★★★★★ (2,156)\n300+ Products',
      x: 280,
      y: 450,
      width: 220,
      height: 180,
      backgroundColor: '#f9f9f9',
      fontSize: 40,
      color: '#1a1a1a',
    },
    {
      id: 'vendor3',
      type: 'container',
      content: '🏠\nHome Essentials\n★★★★☆ (892)\n450+ Products',
      x: 520,
      y: 450,
      width: 220,
      height: 180,
      backgroundColor: '#f9f9f9',
      fontSize: 40,
      color: '#1a1a1a',
    },
    {
      id: 'vendor4',
      type: 'container',
      content: '⚽\nSports Hub\n★★★★★ (1,567)\n320+ Products',
      x: 760,
      y: 450,
      width: 200,
      height: 180,
      backgroundColor: '#f9f9f9',
      fontSize: 40,
      color: '#1a1a1a',
    },
    {
      id: 'deals-title',
      type: 'text',
      content: 'Best Deals Today',
      x: 40,
      y: 670,
      width: 920,
      height: 30,
      fontSize: 24,
      color: '#1a1a1a',
    },
    {
      id: 'deal1',
      type: 'container',
      content: '📱\n50% OFF\n\nSmartphone\n$29.99',
      x: 40,
      y: 720,
      width: 210,
      height: 260,
      backgroundColor: '#ffffff',
      fontSize: 30,
      color: '#ff4444',
    },
    {
      id: 'deal2',
      type: 'container',
      content: '👕\n30% OFF\n\nClothing\n$34.99',
      x: 270,
      y: 720,
      width: 210,
      height: 260,
      backgroundColor: '#ffffff',
      fontSize: 30,
      color: '#ff4444',
    },
    {
      id: 'deal3',
      type: 'container',
      content: '👟\n25% OFF\n\nShoes\n$74.99',
      x: 500,
      y: 720,
      width: 210,
      height: 260,
      backgroundColor: '#ffffff',
      fontSize: 30,
      color: '#ff4444',
    },
    {
      id: 'deal4',
      type: 'container',
      content: '🎮\n45% OFF\n\nGaming Gear\n$54.99',
      x: 730,
      y: 720,
      width: 210,
      height: 260,
      backgroundColor: '#ffffff',
      fontSize: 30,
      color: '#ff4444',
    },
    {
      id: 'footer',
      type: 'container',
      content: '',
      x: 0,
      y: 1020,
      width: 1000,
      height: 80,
      backgroundColor: '#1a1a1a',
    },
    {
      id: 'footer-text',
      type: 'text',
      content: 'Become a Seller | Terms & Conditions | Privacy Policy | Contact Us\n© 2024 MarketHub. All Rights Reserved.',
      x: 40,
      y: 1035,
      width: 920,
      height: 50,
      fontSize: 11,
      color: '#ffffff',
    },
  ],
  tech: [
    // Header
    {
      id: 'header',
      type: 'container',
      content: '',
      x: 0,
      y: 0,
      width: 1000,
      height: 80,
      backgroundColor: '#0f172a',
    },
    {
      id: 'logo',
      type: 'text',
      content: '⚡ TechHub',
      x: 40,
      y: 20,
      width: 250,
      height: 40,
      fontSize: 28,
      color: '#00d4ff',
    },
    {
      id: 'nav-home',
      type: 'button',
      content: 'Home',
      x: 450,
      y: 25,
      width: 60,
      height: 30,
      backgroundColor: 'transparent',
      color: '#e2e8f0',
      fontSize: 13,
    },
    {
      id: 'nav-products',
      type: 'button',
      content: 'Products',
      x: 530,
      y: 25,
      width: 70,
      height: 30,
      backgroundColor: 'transparent',
      color: '#e2e8f0',
      fontSize: 13,
    },
    {
      id: 'nav-deals',
      type: 'button',
      content: 'Deals',
      x: 620,
      y: 25,
      width: 60,
      height: 30,
      backgroundColor: 'transparent',
      color: '#00d4ff',
      fontSize: 13,
    },
    {
      id: 'nav-about',
      type: 'button',
      content: 'About',
      x: 700,
      y: 25,
      width: 60,
      height: 30,
      backgroundColor: 'transparent',
      color: '#e2e8f0',
      fontSize: 13,
    },
    {
      id: 'nav-contact',
      type: 'button',
      content: 'Contact',
      x: 780,
      y: 25,
      width: 70,
      height: 30,
      backgroundColor: 'transparent',
      color: '#e2e8f0',
      fontSize: 13,
    },
    {
      id: 'nav-cart',
      type: 'button',
      content: '🛒 Cart',
      x: 880,
      y: 25,
      width: 80,
      height: 30,
      backgroundColor: '#00d4ff',
      color: '#0f172a',
      fontSize: 12,
    },
    // Hero Section
    {
      id: 'hero',
      type: 'container',
      content: '',
      x: 0,
      y: 80,
      width: 1000,
      height: 240,
      backgroundColor: '#1e293b',
    },
    {
      id: 'hero-accent',
      type: 'container',
      content: '',
      x: 0,
      y: 80,
      width: 1000,
      height: 8,
      backgroundColor: '#00d4ff',
    },
    {
      id: 'hero-text-main',
      type: 'text',
      content: 'Next-Gen Technology',
      x: 50,
      y: 110,
      width: 500,
      height: 50,
      fontSize: 44,
      color: '#f1f5f9',
    },
    {
      id: 'hero-text-sub',
      type: 'text',
      content: 'Cutting-edge devices. Unbeatable prices.',
      x: 50,
      y: 165,
      width: 500,
      height: 35,
      fontSize: 18,
      color: '#cbd5e1',
    },
    {
      id: 'hero-btn',
      type: 'button',
      content: 'EXPLORE NOW →',
      x: 50,
      y: 210,
      width: 160,
      height: 45,
      backgroundColor: '#00d4ff',
      color: '#0f172a',
      fontSize: 13,
    },
    {
      id: 'hero-image',
      type: 'container',
      content: '💻',
      x: 700,
      y: 130,
      width: 220,
      height: 180,
      backgroundColor: '#0f172a',
      fontSize: 100,
      color: '#00d4ff',
    },
    // Category Section
    {
      id: 'category-title',
      type: 'text',
      content: 'SHOP BY CATEGORY',
      x: 40,
      y: 340,
      width: 400,
      height: 35,
      fontSize: 20,
      color: '#0f172a',
    },
    {
      id: 'category1',
      type: 'button',
      content: '💻\nLaptops',
      x: 40,
      y: 390,
      width: 200,
      height: 110,
      backgroundColor: '#e0f2fe',
      color: '#0c4a6e',
      fontSize: 14,
    },
    {
      id: 'category2',
      type: 'button',
      content: '📱\nSmartphones',
      x: 260,
      y: 390,
      width: 200,
      height: 110,
      backgroundColor: '#fce7f3',
      color: '#831843',
      fontSize: 14,
    },
    {
      id: 'category3',
      type: 'button',
      content: '🎧\nAudio',
      x: 480,
      y: 390,
      width: 200,
      height: 110,
      backgroundColor: '#dbeafe',
      color: '#0c4a6e',
      fontSize: 14,
    },
    {
      id: 'category4',
      type: 'button',
      content: '⌚\nWearables',
      x: 700,
      y: 390,
      width: 200,
      height: 110,
      backgroundColor: '#f3e8ff',
      color: '#5b21b6',
      fontSize: 14,
    },
    // Featured Products Section
    {
      id: 'products-title',
      type: 'text',
      content: 'FEATURED PRODUCTS',
      x: 40,
      y: 530,
      width: 400,
      height: 35,
      fontSize: 20,
      color: '#0f172a',
    },
    // Product 1
    {
      id: 'product1-badge',
      type: 'button',
      content: '🔥 HOT DEAL',
      x: 50,
      y: 585,
      width: 80,
      height: 25,
      backgroundColor: '#ff6b6b',
      color: '#ffffff',
      fontSize: 10,
    },
    {
      id: 'product1-img',
      type: 'container',
      content: '💻',
      x: 40,
      y: 620,
      width: 210,
      height: 160,
      backgroundColor: '#f1f5f9',
      fontSize: 80,
      color: '#0f172a',
    },
    {
      id: 'product1-name',
      type: 'text',
      content: 'Pro Ultrabook',
      x: 40,
      y: 795,
      width: 210,
      height: 28,
      fontSize: 15,
      color: '#0f172a',
    },
    {
      id: 'product1-specs',
      type: 'text',
      content: '16" | 32GB RAM | 1TB SSD',
      x: 40,
      y: 825,
      width: 210,
      height: 20,
      fontSize: 11,
      color: '#64748b',
    },
    {
      id: 'product1-price-old',
      type: 'text',
      content: '$1,599.99',
      x: 40,
      y: 850,
      width: 100,
      height: 18,
      fontSize: 11,
      color: '#94a3b8',
    },
    {
      id: 'product1-price',
      type: 'text',
      content: '$1,299.99',
      x: 150,
      y: 848,
      width: 100,
      height: 24,
      fontSize: 16,
      color: '#00d4ff',
    },
    {
      id: 'product1-btn',
      type: 'button',
      content: 'ADD TO CART',
      x: 40,
      y: 880,
      width: 210,
      height: 42,
      backgroundColor: '#0f172a',
      color: '#00d4ff',
      fontSize: 12,
    },
    // Product 2
    {
      id: 'product2-badge',
      type: 'button',
      content: '⭐ TOP RATED',
      x: 270,
      y: 585,
      width: 80,
      height: 25,
      backgroundColor: '#fbbf24',
      color: '#78350f',
      fontSize: 10,
    },
    {
      id: 'product2-img',
      type: 'container',
      content: '📱',
      x: 260,
      y: 620,
      width: 210,
      height: 160,
      backgroundColor: '#f1f5f9',
      fontSize: 80,
      color: '#0f172a',
    },
    {
      id: 'product2-name',
      type: 'text',
      content: 'Flagship Phone',
      x: 260,
      y: 795,
      width: 210,
      height: 28,
      fontSize: 15,
      color: '#0f172a',
    },
    {
      id: 'product2-specs',
      type: 'text',
      content: '6.7" AMOLED | 256GB | 5G',
      x: 260,
      y: 825,
      width: 210,
      height: 20,
      fontSize: 11,
      color: '#64748b',
    },
    {
      id: 'product2-price-old',
      type: 'text',
      content: '$999.99',
      x: 260,
      y: 850,
      width: 100,
      height: 18,
      fontSize: 11,
      color: '#94a3b8',
    },
    {
      id: 'product2-price',
      type: 'text',
      content: '$849.99',
      x: 370,
      y: 848,
      width: 100,
      height: 24,
      fontSize: 16,
      color: '#00d4ff',
    },
    {
      id: 'product2-btn',
      type: 'button',
      content: 'ADD TO CART',
      x: 260,
      y: 880,
      width: 210,
      height: 42,
      backgroundColor: '#0f172a',
      color: '#00d4ff',
      fontSize: 12,
    },
    // Product 3
    {
      id: 'product3-badge',
      type: 'button',
      content: '🎉 NEW',
      x: 490,
      y: 585,
      width: 80,
      height: 25,
      backgroundColor: '#10b981',
      color: '#ffffff',
      fontSize: 10,
    },
    {
      id: 'product3-img',
      type: 'container',
      content: '🎧',
      x: 480,
      y: 620,
      width: 210,
      height: 160,
      backgroundColor: '#f1f5f9',
      fontSize: 80,
      color: '#0f172a',
    },
    {
      id: 'product3-name',
      type: 'text',
      content: 'Premium Earbuds',
      x: 480,
      y: 795,
      width: 210,
      height: 28,
      fontSize: 15,
      color: '#0f172a',
    },
    {
      id: 'product3-specs',
      type: 'text',
      content: 'ANC | 48hr Battery | Hi-Res',
      x: 480,
      y: 825,
      width: 210,
      height: 20,
      fontSize: 11,
      color: '#64748b',
    },
    {
      id: 'product3-rating',
      type: 'text',
      content: '⭐⭐⭐⭐⭐ (342)',
      x: 480,
      y: 845,
      width: 210,
      height: 18,
      fontSize: 11,
      color: '#f59e0b',
    },
    {
      id: 'product3-price',
      type: 'text',
      content: '$349.99',
      x: 480,
      y: 848,
      width: 100,
      height: 24,
      fontSize: 16,
      color: '#00d4ff',
    },
    {
      id: 'product3-btn',
      type: 'button',
      content: 'ADD TO CART',
      x: 480,
      y: 880,
      width: 210,
      height: 42,
      backgroundColor: '#0f172a',
      color: '#00d4ff',
      fontSize: 12,
    },
    // Product 4
    {
      id: 'product4-badge',
      type: 'button',
      content: '⚡ FAST',
      x: 710,
      y: 585,
      width: 80,
      height: 25,
      backgroundColor: '#8b5cf6',
      color: '#ffffff',
      fontSize: 10,
    },
    {
      id: 'product4-img',
      type: 'container',
      content: '⌚',
      x: 700,
      y: 620,
      width: 210,
      height: 160,
      backgroundColor: '#f1f5f9',
      fontSize: 80,
      color: '#0f172a',
    },
    {
      id: 'product4-name',
      type: 'text',
      content: 'Smart Watch Pro',
      x: 700,
      y: 795,
      width: 210,
      height: 28,
      fontSize: 15,
      color: '#0f172a',
    },
    {
      id: 'product4-specs',
      type: 'text',
      content: '2" AMOLED | GPS | 5G Ready',
      x: 700,
      y: 825,
      width: 210,
      height: 20,
      fontSize: 11,
      color: '#64748b',
    },
    {
      id: 'product4-price-old',
      type: 'text',
      content: '$799.99',
      x: 700,
      y: 850,
      width: 100,
      height: 18,
      fontSize: 11,
      color: '#94a3b8',
    },
    {
      id: 'product4-price',
      type: 'text',
      content: '$649.99',
      x: 810,
      y: 848,
      width: 100,
      height: 24,
      fontSize: 16,
      color: '#00d4ff',
    },
    {
      id: 'product4-btn',
      type: 'button',
      content: 'ADD TO CART',
      x: 700,
      y: 880,
      width: 210,
      height: 42,
      backgroundColor: '#0f172a',
      color: '#00d4ff',
      fontSize: 12,
    },
    // Promo Section
    {
      id: 'promo-section',
      type: 'container',
      content: '',
      x: 0,
      y: 960,
      width: 1000,
      height: 120,
      backgroundColor: '#0f172a',
    },
    {
      id: 'promo-accent',
      type: 'container',
      content: '',
      x: 0,
      y: 960,
      width: 1000,
      height: 4,
      backgroundColor: '#00d4ff',
    },
    {
      id: 'promo-text',
      type: 'text',
      content: '🚚 FREE SHIPPING on orders over $100 | ✨ 2-YEAR WARRANTY | 🔄 30-DAY RETURNS',
      x: 40,
      y: 990,
      width: 920,
      height: 50,
      fontSize: 14,
      color: '#e2e8f0',
    },
    // Footer
    {
      id: 'footer',
      type: 'container',
      content: '',
      x: 0,
      y: 1080,
      width: 1000,
      height: 100,
      backgroundColor: '#0a0f1f',
    },
    {
      id: 'footer-col1',
      type: 'text',
      content: 'PRODUCTS\n• Laptops\n• Phones\n• Audio',
      x: 40,
      y: 1100,
      width: 220,
      height: 60,
      fontSize: 11,
      color: '#cbd5e1',
    },
    {
      id: 'footer-col2',
      type: 'text',
      content: 'SUPPORT\n• Help Center\n• Contact Us\n• Warranty',
      x: 280,
      y: 1100,
      width: 220,
      height: 60,
      fontSize: 11,
      color: '#cbd5e1',
    },
    {
      id: 'footer-col3',
      type: 'text',
      content: 'COMPANY\n• About Us\n• Careers\n• Press',
      x: 520,
      y: 1100,
      width: 220,
      height: 60,
      fontSize: 11,
      color: '#cbd5e1',
    },
    {
      id: 'footer-info',
      type: 'text',
      content: '© 2024 TechHub. All rights reserved. | support@techhub.com | 1-800-TECH-HUB',
      x: 40,
      y: 1155,
      width: 920,
      height: 20,
      fontSize: 10,
      color: '#64748b',
    },
  ],
};
